name: neura_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.3.0+4

environment:
  sdk: ^3.7.0

dependencies:
  convert: ^3.1.2
  crypto: ^3.0.6
  dartz: ^0.10.1
  dio: ^5.8.0+1
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_native_splash: ^2.4.5
  flutter_secure_storage: ^4.2.1
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  go_router: ^14.8.0
  gpt_markdown: ^1.0.11
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#181A20"
  color_dark: "#181A20"

  image: assets/app/splash.png
  image_dark: assets/app/splash.png

  android_12:
    image: assets/app/splash.png
    image_dark: assets/app/splash.png
    color: "#181A20"
    color_dark: "#181A20"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 800
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-ExtraLight.ttf
          weight: 200